apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: monitoring
spec:
  selector:
    app: webhook-alertmanager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
