global:
  scrape_interval: 15s
  
rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api-monitorada'
    static_configs:
      - targets: ['app:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
        - targets: ['app:8000']