apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
      - name: default
        webhook_configs:
          - url: 'http://webhook-alertmanager.monitoring.svc:5000/'
