version: '3'
services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # volumes:
    #   - ./custom.ini:/etc/grafana/custom.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin@123
      # - GF_PATHS_CONFIG=/etc/grafana/custom.ini