apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: x509-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: x509-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 30s
