apiVersion: v1
kind: Service
metadata:
  name: x509-exporter
  namespace: monitoring
  labels:
    app: x509-exporter
spec:
  ports:
    - name: http
      port: 9793
      targetPort: 9793
  selector:
    app: x509-exporter
