apiVersion: v1
kind: ServiceAccount
metadata:
  name: x509-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: x509-exporter
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: x509-exporter
roleRef:
  kind: ClusterRole
  name: x509-exporter
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: x509-exporter
    namespace: monitoring
